INSERT INTO silver.state_region (state_, region)
VALUES	('AC', 'norte'),
		('AP', 'norte'),
		('AM', 'norte'),
		('PA', 'norte'),
		('RO', 'norte'),
		('RR', 'norte'),
		('TO', 'norte'),
		('AL', 'nordeste'),
		('BA', 'nordeste'),
		('CE', 'nordeste'),
		('MA', 'nordeste'),
		('PB', 'nordeste'),
		('PE', 'nordeste'),
		('PI', 'nordeste'),
		('RN', 'nordeste'),
		('SE', 'nordeste'),
		('DF', 'centro-oeste'),
		('GO', 'centro-oeste'),
		('MT', 'centro-oeste'),
		('MS', 'centro-oeste'),
		('ES', 'sudeste'),
		('MG', 'sudeste'),
		('RJ', 'sudeste'),
		('SP', 'sudeste'),
		('PR', 'sul'),
		('RS', 'sul'),
		('SC', 'sul')
ON CONFLICT (state_) DO NOTHING;